FROM ubuntu:18.04

# install packages
RUN apt update && \
apt install -y curl

# Install node_exporter
ENV NODE_VERSION=node_exporter-1.5.0.linux-amd64
RUN useradd prometheus && \
mkdir -p /opt/prometheus/node_exporter/

# download new version
RUN curl -sSL https://github.com/prometheus/node_exporter/releases/download/v1.5.0/${NODE_VERSION}.tar.gz | tar xfz - -C /tmp
RUN cp /tmp/${NODE_VERSION}/node_exporter /opt/prometheus/node_exporter/
RUN chown prometheus:prometheus /opt/prometheus/node_exporter/node_exporter

EXPOSE 9109
# run node_exporter
ENTRYPOINT ["/opt/prometheus/node_exporter/node_exporter", "--web.listen-address=:9109"]
